copy .\2ship.png .\working\
copy .\3do.png .\working\
copy .\3doj.png .\working\
copy .\3ds.png .\working\
copy .\aae.png .\working\
copy .\actionmax.png .\working\
copy .\adam.png .\working\
copy .\adrenalinepc.png .\working\
copy .\advision.png .\working\
copy .\alphadenshi.png .\working\
copy .\amazon.png .\working\
copy .\amiga1200.png .\working\
copy .\amiga4000.png .\working\
copy .\amiga500.png .\working\
copy .\amigacd32.png .\working\
copy .\amigacdtv.png .\working\
copy .\amstradcpc.png .\working\
copy .\apfm1000.png .\working\
copy .\apple2.png .\working\
copy .\apple2gs.png .\working\
copy .\aquarius.png .\working\
copy .\arcade.png .\working\
copy .\arcadedumps.png .\working\
copy .\arcadia.png .\working\
copy .\archimedes.png .\working\
copy .\arduboy.png .\working\
copy .\astrocade.png .\working\
copy .\atari.png .\working\
copy .\atari2600.png .\working\
copy .\atari5200.png .\working\
copy .\atari7800.png .\working\
copy .\atari800.png .\working\
copy .\atarijaguar.png .\working\
copy .\atarijaguarcd.png .\working\
copy .\atarilynx.png .\working\
copy .\atarist.png .\working\
copy .\atlus.png .\working\
copy .\atom.png .\working\
copy .\atomiswave.png .\working\
copy .\auto-action.png .\working\
copy .\auto-adult.png .\working\
copy .\auto-adventure.png .\working\
copy .\auto-asiaticboard.png .\working\
copy .\auto-beatemup.png .\working\
copy .\auto-casino.png .\working\
copy .\auto-casual.png .\working\
copy .\auto-demo.png .\working\
copy .\auto-educational.png .\working\
copy .\auto-fight.png .\working\
copy .\auto-huntingandfishing.png .\working\
copy .\auto-musicanddance.png .\working\
copy .\auto-pinball.png .\working\
copy .\auto-platform.png .\working\
copy .\auto-playingcards.png .\working\
copy .\auto-puzzle.png .\working\
copy .\auto-quiz.png .\working\
copy .\auto-racedriving.png .\working\
copy .\auto-reflection.png .\working\
copy .\auto-roleplayings.png .\working\
copy .\auto-shootemup.png .\working\
copy .\auto-shooter.png .\working\
copy .\auto-simulation.png .\working\
copy .\auto-sports.png .\working\
copy .\auto-sportswithanimals.png .\working\
copy .\auto-strategy.png .\working\
copy .\auto-various.png .\working\
copy .\bandai.png .\working\
copy .\banpresto.png .\working\
copy .\bbcmicro.png .\working\
copy .\bennugd.png .\working\
copy .\bigfish.png .\working\
copy .\boom3.png .\working\
copy .\bstone.png .\working\
copy .\bsyndrome.png .\working\
copy .\btm.png .\working\
copy .\c128.png .\working\
copy .\c16.png .\working\
copy .\c20.png .\working\
copy .\c64.png .\working\
copy .\camplynx.png .\working\
copy .\cannonball.png .\working\
copy .\capcom.png .\working\
copy .\casino.png .\working\
copy .\cassettevision.png .\working\
copy .\cave.png .\working\
copy .\cavestory.png .\working\
copy .\cdi.png .\working\
copy .\cdogs.png .\working\
copy .\cgenius.png .\working\
copy .\channelf.png .\working\
copy .\chero.png .\working\
copy .\chihiro.png .\working\
copy .\cinematronics.png .\working\
copy .\coco.png .\working\
copy .\colecovision.png .\working\
copy .\comad.png .\working\
copy .\corsixth.png .\working\
copy .\cplus4.png .\working\
copy .\cps1.png .\working\
copy .\cps2.png .\working\
copy .\cps3.png .\working\
copy .\creativision.png .\working\
copy .\daphne.png .\working\
copy .\dataeast.png .\working\
copy .\ddr.png .\working\
copy .\devilutionx.png .\working\
copy .\dice.png .\working\
copy .\dinothawr.png .\working\
copy .\doom3.png .\working\
copy .\dragon32.png .\working\
copy .\dreamcast.png .\working\
copy .\eagames.png .\working\
copy .\easyrpg.png .\working\
copy .\ecwolf.png .\working\
copy .\eduke32.png .\working\
copy .\eighting.png .\working\
copy .\electron.png .\working\
copy .\elektronika.png .\working\
copy .\emteck.png .\working\
copy .\enterprise.png .\working\
copy .\epic.png .\working\
copy .\examu.png .\working\
copy .\exidy.png .\working\
copy .\expotato.png .\working\
copy .\fbneo.png .\working\
copy .\fc.png .\working\
copy .\fds.png .\working\
copy .\fightcade.png .\working\
copy .\flash.png .\working\
copy .\fm7.png .\working\
copy .\fmtowns.png .\working\
copy .\fpinball.png .\working\
copy .\fruit.png .\working\
copy .\gaelco.png .\working\
copy .\gaelcog.png .\working\
copy .\gamate.png .\working\
copy .\gameandwatch.png .\working\
copy .\gamecom.png .\working\
copy .\gamegear.png .\working\
copy .\gamegearh.png .\working\
copy .\gamepock.png .\working\
copy .\gamewax.png .\working\
copy .\gb-msu.png .\working\
copy .\gb.png .\working\
copy .\gb2players.png .\working\
copy .\gba.png .\working\
copy .\gba2players.png .\working\
copy .\gbc.png .\working\
copy .\gbc2players.png .\working\
copy .\gc.png .\working\
copy .\gemrb.png .\working\
copy .\genesis.png .\working\
copy .\globalvr.png .\working\
copy .\gmaster.png .\working\
copy .\gog.png .\working\
copy .\gottlieb.png .\working\
copy .\gp32.png .\working\
copy .\gx4000.png .\working\
copy .\gzdoom.png .\working\
copy .\halflife.png .\working\
copy .\hbmame.png .\working\
copy .\hikaru.png .\working\
copy .\igs.png .\working\
copy .\ikemen.png .\working\
copy .\imageviewer.png .\working\
copy .\incredibletech.png .\working\
copy .\intellivision.png .\working\
copy .\ique.png .\working\
copy .\irem.png .\working\
copy .\j2me.png .\working\
copy .\jakks.png .\working\
copy .\jaleco.png .\working\
copy .\kaneko.png .\working\
copy .\karaoke.png .\working\
copy .\konami.png .\working\
copy .\konamih.png .\working\
copy .\konamipc.png .\working\
copy .\laseractive.png .\working\
copy .\lcdgames.png .\working\
copy .\library.png .\working\
copy .\locomalito.png .\working\
copy .\loopy.png .\working\
copy .\love.png .\working\
copy .\lowresnx.png .\working\
copy .\lutro.png .\working\
copy .\m5.png .\working\
copy .\magazine.png .\working\
copy .\mame.png .\working\
copy .\mastersystem.png .\working\
copy .\mastersystemfm.png .\working\
copy .\mastersystemh.png .\working\
copy .\megacd.png .\working\
copy .\megadrive-msu.png .\working\
copy .\megadrive.png .\working\
copy .\megadriveh.png .\working\
copy .\megaduck.png .\working\
copy .\mess.png .\working\
copy .\midway.png .\working\
copy .\mitchell.png .\working\
copy .\model2.png .\working\
copy .\model3.png .\working\
copy .\msx1.png .\working\
copy .\msx2.png .\working\
copy .\msx2+.png .\working\
copy .\msxturbor.png .\working\
copy .\mugen.png .\working\
copy .\multivision.png .\working\
copy .\n64.png .\working\
copy .\n64dd.png .\working\
copy .\n64h.png .\working\
copy .\n64j.png .\working\
copy .\namco.png .\working\
copy .\namco22.png .\working\
copy .\namco2x6.png .\working\
copy .\namco357.png .\working\
copy .\namco3xx.png .\working\
copy .\namcoarcade.png .\working\
copy .\naomi.png .\working\
copy .\naomi2.png .\working\
copy .\nds.png .\working\
copy .\neogeo.png .\working\
copy .\neogeo64.png .\working\
copy .\neogeoaes.png .\working\
copy .\neogeocd.png .\working\
copy .\neogeoh.png .\working\
copy .\nes.png .\working\
copy .\nes3d.png .\working\
copy .\nesb.png .\working\
copy .\nesh.png .\working\
copy .\neshd.png .\working\
copy .\nesicaxlive.png .\working\
copy .\ngage.png .\working\
copy .\ngp.png .\working\
copy .\ngpc.png .\working\
copy .\nichibutsu.png .\working\
copy .\nintendo.png .\working\
copy .\nmk.png .\working\
copy .\odyssey2.png .\working\
copy .\openbor.png .\working\
copy .\opengoal.png .\working\
copy .\openjazz.png .\working\
copy .\openlara.png .\working\
copy .\oric.png .\working\
copy .\ouya.png .\working\
copy .\p2000t.png .\working\
copy .\palm.png .\working\
copy .\pc.png .\working\
copy .\pc88.png .\working\
copy .\pc98.png .\working\
copy .\pce-cd.png .\working\
copy .\pcengine.png .\working\
copy .\pcfx.png .\working\
copy .\pdark.png .\working\
copy .\pegasus.png .\working\
copy .\pet.png .\working\
copy .\pico8.png .\working\
copy .\pinballfx.png .\working\
copy .\pinballfx2.png .\working\
copy .\pinballfx3.png .\working\
copy .\pinballm.png .\working\
copy .\pippin.png .\working\
copy .\pockstat.png .\working\
copy .\pokemini.png .\working\
copy .\popcap.png .\working\
copy .\ports.png .\working\
copy .\powerbomberman.png .\working\
copy .\prboom.png .\working\
copy .\ps2.png .\working\
copy .\ps2br.png .\working\
copy .\ps2h.png .\working\
copy .\ps3.png .\working\
copy .\ps3br.png .\working\
copy .\ps3j.png .\working\
copy .\ps4.png .\working\
copy .\ps5.png .\working\
copy .\psikyo.png .\working\
copy .\psp.png .\working\
copy .\pspminis.png .\working\
copy .\psvita.png .\working\
copy .\psx.png .\working\
copy .\psxh.png .\working\
copy .\pv1000.png .\working\
copy .\quake.png .\working\
copy .\quake2.png .\working\
copy .\rawthrills.png .\working\
copy .\raze.png .\working\
copy .\reminiscence.png .\working\
copy .\retrobat.png .\working\
copy .\ritual.png .\working\
copy .\rtcw.png .\working\
copy .\samcoupe.png .\working\
copy .\sammy.png .\working\
copy .\satellaview.png .\working\
copy .\saturn.png .\working\
copy .\screenshots.png .\working\
copy .\scummvm.png .\working\
copy .\scv.png .\working\
copy .\sega.png .\working\
copy .\sega32x.png .\working\
copy .\sega32xh.png .\working\
copy .\segaages2500.png .\working\
copy .\segaalls.png .\working\
copy .\segacd.png .\working\
copy .\segaeuropar.png .\working\
copy .\segalindbergh.png .\working\
copy .\seganu2.png .\working\
copy .\segapc.png .\working\
copy .\segaringedge.png .\working\
copy .\segaringwide.png .\working\
copy .\segastv.png .\working\
copy .\seibukaihatsu.png .\working\
copy .\semicom.png .\working\
copy .\seta.png .\working\
copy .\sfc.png .\working\
copy .\sg-1000.png .\working\
copy .\sgb-msu1.png .\working\
copy .\sgb.png .\working\
copy .\singe.png .\working\
copy .\snes-msu1.png .\working\
copy .\snes.png .\working\
copy .\snesh.png .\working\
copy .\snk.png .\working\
copy .\socrates.png .\working\
copy .\soh.png .\working\
copy .\solarus.png .\working\
copy .\sonic-mania.png .\working\
copy .\sonic3-air.png .\working\
copy .\sonicretro.png .\working\
copy .\spectravideo.png .\working\
copy .\starship.png .\working\
copy .\steam.png .\working\
copy .\sufami.png .\working\
copy .\superbroswar.png .\working\
copy .\supercharger.png .\working\
copy .\supergrafx.png .\working\
copy .\supervision.png .\working\
copy .\supracan.png .\working\
copy .\svmu.png .\working\
copy .\switch.png .\working\
copy .\switch2.png .\working\
copy .\taito.png .\working\
copy .\taitox.png .\working\
copy .\technos.png .\working\
copy .\tecmo.png .\working\
copy .\teknoparrot.png .\working\
copy .\tg16.png .\working\
copy .\tg16cd.png .\working\
copy .\theforceengine.png .\working\
copy .\thextech.png .\working\
copy .\thomson.png .\working\
copy .\ti99.png .\working\
copy .\tic80.png .\working\
copy .\tiger.png .\working\
copy .\tigerrz.png .\working\
copy .\toaplan.png .\working\
copy .\touhou.png .\working\
copy .\triforce.png .\working\
copy .\triotech.png .\working\
copy .\turboduo.png .\working\
copy .\tutor.png .\working\
copy .\tvgames.png .\working\
copy .\tyrquake.png .\working\
copy .\unianapc.png .\working\
copy .\uniquepc.png .\working\
copy .\unis.png .\working\
copy .\unity.png .\working\
copy .\universal.png .\working\
copy .\uzebox.png .\working\
copy .\vc4000.png .\working\
copy .\vectrex.png .\working\
copy .\vg5k.png .\working\
copy .\vircon32.png .\working\
copy .\virtualboy.png .\working\
copy .\visco.png .\working\
copy .\vitaquake2.png .\working\
copy .\vpinball.png .\working\
copy .\vsc.png .\working\
copy .\vsmile.png .\working\
copy .\wahlap.png .\working\
copy .\wasm4.png .\working\
copy .\wii.png .\working\
copy .\wiih.png .\working\
copy .\wiiu-sky.png .\working\
copy .\wiiu.png .\working\
copy .\wiiware.png .\working\
copy .\win98.png .\working\
copy .\windows.png .\working\
copy .\windows9x.png .\working\
copy .\wonderswan.png .\working\
copy .\wonderswancolor.png .\working\
copy .\x1.png .\working\
copy .\x68000.png .\working\
copy .\xbox.png .\working\
copy .\xbox360.png .\working\
copy .\xboxlivearcade.png .\working\
copy .\xegs.png .\working\
copy .\zaccariapinball.png .\working\
copy .\zeebo.png .\working\
copy .\zinc.png .\working\
copy .\zmachine.png .\working\
copy .\zx81.png .\working\
copy .\zxspectrum.png .\working\
copy .\custom-collections.png .\working\
copy .\msx2+.png .\working\
copy .\auto-at2players.png .\working\
copy .\auto-at4players.png .\working\
copy .\auto-allgames.png .\working\
copy .\auto-favorites.png .\working\
copy .\auto-lastplayed.png .\working\
copy .\auto-lightgun.png .\working\
copy .\auto-neverplayed.png .\working\
copy .\auto-recent.png .\working\
copy .\auto-retroachievements.png .\working\
copy .\auto-spinner.png .\working\
copy .\auto-trackball.png .\working\
copy .\auto-verticalarcade.png .\working\
copy .\auto-wheel.png .\working\
